language: php
sudo: false
cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/symfony-bridge/.phpunit
env:
  global:
    - PHPUNIT_FLAGS="-v"
    - SYMFONY_PHPUNIT_DIR="$HOME/symfony-bridge/.phpunit"
matrix:
  fast_finish: true
  include:
    # Run test with code coverage
    - php: 7.3
      env: COVERAGE=false # needs to be re-enabled

      # Test with lowest dependencies
    - php: 7.2
      env: COMPOSER_FLAGS="--prefer-lowest"

      # Test the latest stable release
    - php: 7.3
    - php: 7.4

      # Force some major versions of Symfony
    - php: 7.3
      env: SYMFONY_VERSION="4.*"
    - php: 7.3
      env: SYMFONY_VERSION="5.*"

      # Latest commit to master
    - php: 7.3
      env: STABILITY="dev"

  allow_failures:
    # Dev-master is allowed to fail.
    - env: STABILITY="dev"

before_install:
  - if [[ $COVERAGE != true ]]; then phpenv config-rm xdebug.ini || true; fi
  - if ! [ -z "$STABILITY" ]; then composer config minimum-stability ${STABILITY}; fi;
  - if ! [ -v "$DEPENDENCIES" ]; then composer require --no-update ${DEPENDENCIES}; fi;
install:
  - composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction
script:
  - composer validate --strict --no-check-lock
  - if [[ $COVERAGE = true ]]; then ./vendor/bin/phpunit --coverage-clover=coverage.clover; else ./vendor/bin/phpunit; fi


after_success:
  - if [[ $COVERAGE = true ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ $COVERAGE = true ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
